# Generated by Django 4.1.2 on 2022-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
